server:
  port: 8002
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: fac123
    url: jdbc:postgresql://localhost:5432/msvc_cursos

  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
logging:
  level:
    org:
      hibernate:
        SQL: debug
