server:
  port: 8002
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/msvc_usuarios
    username: root
    password:
  jpa:
   hibernate:
    ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
 application:
  name: msvc-usuarios
